version: "3.8"

services:
  dev-portfolio-web:
    container_name: dev-porfolio-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - .:/srv/www/html
